"""Reusable paper-figure templates derived from the imported style library."""

from paper_plot_library import (
    apply_paper_style,
    broken_axis_scatter,
    clustered_scatter,
    grouped_bar,
    heat_value_table,
    line_with_band,
    line_with_inset,
    paired_delta_bar,
    radar_comparison,
    save_paper_figure,
)

from extended_templates import (
    annual_risk_trend,
    correlation_heatmap,
    diverging_bar,
    ecdf_risk_comparison,
    lollipop_ranking,
    observed_predicted_scatter,
    paired_difference_stats,
    paired_difference_distribution,
    pareto_front,
    process_flowchart,
    residual_scatter,
    risk_boxplot,
    sensitivity_curve,
    sensitivity_tornado,
    spatial_bubble,
    stacked_composition_bar,
)
__all__ = [
    "apply_paper_style",
    "broken_axis_scatter",
    "clustered_scatter",
    "grouped_bar",
    "heat_value_table",
    "line_with_band",
    "line_with_inset",
    "paired_delta_bar",
    "radar_comparison",
    "save_paper_figure",
    "annual_risk_trend",
    "correlation_heatmap",
    "diverging_bar",
    "ecdf_risk_comparison",
    "lollipop_ranking",
    \
    "paired_difference_distribution",
    "pareto_front",
    "process_flowchart",
    "residual_scatter",
    "risk_boxplot",
    "sensitivity_curve",
    "sensitivity_tornado",
    "spatial_bubble",
    "stacked_composition_bar",
]
